### ISSUE TITLE
Integration with Huggingface Trainer

### ISSUE THREAD

**Issue by z-bookworm** [thunlp/OpenDelta#11]
Hi,

I wonder what's the correct way to integrate this library into [Huggingface Trainer](https://huggingface.co/docs/transformers/main_classes/trainer)?

Does it work out of the box? Or we need to explictly save the delta parameters. For example, implement  a model saving callback after each evaluation.

**Comment by ShengdingHu** [comment]
In case you have a script based on Huggingface trainer, just modify the model after the model is loaded, that is enough. OpenDelta works out of the box, it changes the state_dict to the tunable part of the model, so no additional effort should be paid to edit the training loop.
