### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by duyvuleo** [thunlp/OpenDelta#15]
Dear authors,

Thanks for the useful toolkit.

Would you mind specifying the LICENSE of this toolkit? Thanks!

**Comment by ShengdingHu** [comment]
Sure， we will look into it as soon as possible

**Comment by ningding97** [comment]
> Dear authors,
> 
> Thanks for the useful toolkit.
> 
> Would you mind specifying the LICENSE of this toolkit? Thanks!

We have added Apache 2.0 license, thanks!
