### ISSUE TITLE
error when running on multiple cards

### ISSUE THREAD

**Issue by wangdeze18** [thunlp/OpenDelta#18]
When running the program with the adapter inserted on multiple cards, 
`from opendelta import AdapterModel`
`delta_model = AdapterModel(backbone_model=model, modified_modules=['fc2'], bottleneck_dim=12)`

the following error occurs, 
`RuntimeError: Caught RuntimeError in replica 0 on device 0.`
and when transferred to a single card to run, no more errors are reported.

**Comment by ShengdingHu** [comment]
Could you please provide more information?  Are you using data-parallel or model-parallel?
