### ISSUE TITLE
`index.html` is not included in the package if installing from PyPI

### ISSUE THREAD

**Issue by Spico197** [thunlp/OpenDelta#19]
Thanks for the excellent package.

## Problem

The `index.html` file in `opendelta/utils/interactive/templates/` is a static file, and it will not be included in the distributed package file (like the wheel file) unless you add the package data manually in `setup.py`.

## Reproduce

On a clean environment,
```bash
$ pip install opendelta
$ python examples/tutorial/0_interactive.py
```

**Comment by Spico197** [comment]
Fair enough. I thought there would be a discussion on this issue, but this was closed without any explanations or discussions. Besides, the problem still remains.

**Comment by ShengdingHu** [comment]
Sorry for the inconvenience, we need to temporarily close the issue for some other reasons. We are working on addressing existing issues and improving the toolkit.

**Comment by ShengdingHu** [comment]
We have fixed this issue together with some other issues in the [newest commit](https://github.com/thunlp/OpenDelta/commit/f56dd68bb68aa0c6a89a6087695c7d059a552d73). We also publish a new pip version opendelta==0.1.0   Please check, thanks!
