### ISSUE TITLE
`sequential` parameter is not used in `AdapterModel`

### ISSUE THREAD

**Issue by alvin870203** [thunlp/OpenDelta#20]
Hi,

Thanks for the awesome tool!
I noticed that the `sequential: Optional[str]=True` parameter in the `AdapterModel` is not used,
so the user can not actually insert the adapter in a parallel manner for the `AdapterModel` class by setting `sequntial=False`.
I think it's a little bit confusing for the user.
Maybe you can add the `insert_parallel_module()` function to the `AdapterModel` class,
or just don't let the user to be able to set the `sequential` parameter when initializing the `AdapterModel` class.

**Comment by ShengdingHu** [comment]
Thanks for pointing it out. Actually, we are developing a parallel version of the adapter model. The branch will be merged soon.
