### ISSUE TITLE
Reproduce Prompt Tuning results

### ISSUE THREAD

**Issue by ethankim00** [thunlp/OpenDelta#3]
Can this reproduce results on SuperGLUE from  The Power of Scale for Parameter-Efficient Prompt Tuning https://arxiv.org/pdf/2104.08691.pdf

**Comment by wxj630** [comment]
when i use SoftPromptModel, text length=400 and prompt token length=100,but raise an error, can anyone tell me why?
`File "/home/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 217, in forward
    embeddings = inputs_embeds + token_type_embeddings
RuntimeError: The size of tensor a (500) must match the size of tensor b (400) at non-singleton dimension 1`

**Comment by ShengdingHu** [comment]
We will soon report the results in our paper.
