### ISSUE TITLE
json.decoder.JSONDecodeError when calling DeltaCente.OssClient.download function

### ISSUE THREAD

**Issue by Hemuhui** [thunlp/OpenDelta#36]
A JSONDecodeError occurred  when I ran the commands below:

![image](https://user-images.githubusercontent.com/116062005/196612363-743daec3-d3b0-4433-840c-f6716caedcb1.png)

![image](https://user-images.githubusercontent.com/116062005/196360059-25da2b85-7037-47db-8af7-e26641176e79.png)
Need your help :)
the delta-center-client version is 0.0.4.

**Comment by ShengdingHu** [comment]
Can you post the commands or scripts? Thanks！

**Comment by ShengdingHu** [comment]
What's the version of OpenDelta? Can you try the following command to update the opendelta?
```
pip uninstall opendetla 
pip install git+https://github.com/thunlp/OpenDelta.git
```
I also make a [jupyter notebook for must_try.py](https://colab.research.google.com/drive/1Nbe9zxt8LGQnKmtvEs07IN_PznjNCyk4?usp=sharing).
