### ISSUE TITLE
初始化基类时，如果填了unfrozen_modules，没有unfrozen_modules赋值

### ISSUE THREAD

**Issue by dabaoka** [thunlp/OpenDelta#38]
初始化基类时，如果传入unfrozen_modules，没有使用它赋值。
![image](https://user-images.githubusercontent.com/38815187/198179556-7ecd031f-35d8-4c0b-a484-8406627df3fe.png)

**Comment by ShengdingHu** [comment]
Many thanks for pointing out the bug!
