### ISSUE TITLE
Can OpenDelta execute on CUDA?

### ISSUE THREAD

**Issue by wangbing1416** [thunlp/OpenDelta#4]
When I add `.to('cuda')` to my backbone T5, there is a bug as follow:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
`

And I check the source code in `opendelta.delta_models.soft_prompt`, some variables are not send to 'cuda', for example:
`soft_embeds.data = torch.clone(self.raw_embedding(torch.tensor([i for i in range(self.num_tokens)])))`

Although I have solved this problem, I want to know : is it a **BUG** of OpenDelta? or my misunderstanding？

**Comment by Lancelot39** [comment]
I want to ask how you solve this problem. I have just met the same issue as you.

> When I add `.to('cuda')` to my backbone T5, there is a bug as follow: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select) `
> 
> And I check the source code in `opendelta.delta_models.soft_prompt`, some variables are not send to 'cuda', for example: `soft_embeds.data = torch.clone(self.raw_embedding(torch.tensor([i for i in range(self.num_tokens)])))`
> 
> Although I have solved this problem, I want to know : is it a **BUG** of OpenDelta? or my misunderstanding？
