### ISSUE TITLE
Is it possible to extract the Visualization module as an independent python packages?

### ISSUE THREAD

**Issue by Dounm** [thunlp/OpenDelta#40]
`Visualization(mode).structure_graph()` is especially useful to view the large language models, and sometimes I would like to use it in some other scenario.

So instead of install the whole `OpenDelta`, is it possible to isolate the `Visualization` functionality from `OpenDelta`, then it can become more light-weight and more easily to install ?

**Comment by ShengdingHu** [comment]
Thanks for you suggestion. I will prepare it soon.

**Comment by zt-wang19** [comment]
@Dounm We've solved this issue in this commit:

**Comment by zt-wang19** [comment]
@Dounm We've solved the issue in this commit:
https://github.com/thunlp/OpenDelta/tree/ecbfc0f2449586db41f01cb69f3f080fb3e1a474
And we've also upload the visualization module to PyPI. You can first `pip install bigmodelvis`, and then use the code below to visualize your model:
```
from bigmodelvis import Visualization
from transformers import BertForMaskedLM
model = BertForMaskedLM.from_pretrained('bert-base-uncased')
visobj = Visualization(model)
visobj.structure_graph()
```
