### ISSUE TITLE
通过setup.py安装提示error: aiohttp 4.0.0a0 is installed but aiohttp!=4.0.0a0,!=4.0.0a1 is required by {'fsspec'}

### ISSUE THREAD

**Issue by daliang0222** [thunlp/OpenDelta#45]
Installed /home/bmxm/anaconda3/envs/cpm-ant-plus/lib/python3.8/site-packages/opendelta-0.3.2-py3.8.egg
Processing dependencies for opendelta==0.3.2
error: aiohttp 4.0.0a0 is installed but aiohttp!=4.0.0a0,!=4.0.0a1 is required by {'fsspec'}
![image](https://user-images.githubusercontent.com/19166994/203706652-c5cd2208-863b-4b3d-98b3-569ee7159bae.png)

**Comment by Achazwl** [comment]
Which python version do you use?
