### ISSUE TITLE
What is the difference between OpenDelta and adapter-transformers?

### ISSUE THREAD

**Issue by fighterhit** [thunlp/OpenDelta#46]
Hi team, recently I was investigating the method of fine-tuning the PTMs using an `adapter(delta)` model. I found the functions implemented by `OpenDelta` and [`adapter-transformers`](https://github.com/adapter-hub/adapter-transformers) are similar. Is there any difference between them? Thanks!

**Comment by ShengdingHu** [comment]
Thanks for your interest. The key difference is that opendelta is a package that does not modify the pre-trained models' code, which means that it has the potential to be applied to any pytorch models with transformers architecture, even the newly emerging ones. Adapter-transformers modifies codes of huggingface transformers in its implementation.  For the key features, see [Why OpenDelta](https://opendelta.readthedocs.io/en/latest/notes/overview.html).
