### ISSUE TITLE
Failed to load adapter layer using OpenDelta+BMTrain

### ISSUE THREAD

**Issue by XWang20** [thunlp/OpenDelta#54]
## Environment:
python=3.7, pytorch=1.13.0+cu117, bmtrain=0.2.1, model_center=1.0.0, opendelta=0.3.2

## Description:
- I am encountering an issue while loading a trained adapter layer using OpenDelta and BMTrain. I am trying to load saved parameters from disk. But the adapter layer is not getting loaded, and I am getting an "unexpected key" message from the load_state_dict() function. 
- The saved parameters include adapter layer and classifier layer. The classifier layer is getting loaded correctly, while the adapter layer is not loaded.
- The saved parameters and the same layer in the model are not the same, indicating that the model has not loaded the saved parameters correctly:
![image](https://user-images.githubusercontent.com/43691322/226150418-16c03438-36d2-4992-9a47-b389d59f62fc.png)
## Code:

```python
# load from huggingface
model = DebertaV2ForSequenceClassification.from_pretrained("microsoft/deberta-v2-xxlarge", torch_dtype=torch.float16, num_labels=2)

# bmtrain wrapper
model = bmt.BMTrainModelWrapper(model)

# add adapter
delta_model = AdapterModel(backbone_model=model, modified_modules=['output'], backend='bmt')
delta_model.freeze_module(exclude=["deltas", "classifier"], set_state_dict=True)

# load adapter weights
model.load_state_dict(torch.load(args.model_path), strict=False)
```

**Comment by ShengdingHu** [comment]
Thanks for pointing out this issue! This issue can be solved by using another bmtrain version https://github.com/Achazwl/BMTrain/tree/tempfix_opendelta
