### ISSUE TITLE
cannot import name 'Visualization' from 'opendelta'

### ISSUE THREAD

**Issue by skye95git** [thunlp/OpenDelta#74]
I install the latest version by `pip install git+https://github.com/thunlp/OpenDelta.git`, but it can't import name 'Visualization' from 'opendelta'.
<img width="453" alt="image" src="https://github.com/thunlp/OpenDelta/assets/41561936/928008e0-8813-4aab-a9f0-3e22ae60a932">

**Comment by helloxcq** [comment]
May be you should import Visualization like that
`from bigmodelvis import Visualization`
