### ISSUE TITLE
Differences between Houlsby and Pfeiffer adapters

### ISSUE THREAD

**Issue by ImKeTT** [thunlp/OpenDelta#8]
Thanks for providing such a great work here! There are structural differences between Houlsby and Pfeiffer adapters (Houlsby et al. places two adapters sequentially within one layer of the transformer, one after the multi-head attention and one after the FFN sub-layer, while Pfeiffer et al. adapter is inserted only after the FFN “add & layer norm” sub-layer), which seems to be missed in the code.

**Comment by ShengdingHu** [comment]
Actually, you can choose your own positions to place the adapter. Both Houlsby and Pfeiffer styles can be configured, just set the modified_modules=['attention', 'ff'] or modified_modules=['layer_norm'] (different w.r.t different architectures, please use the visualization module to visualize the architecture). You can even apply adapter drop with modified_modules set to ["6.attention", "7.attention", ...]

**Comment by ImKeTT** [comment]
right I see, thanks for replying.

> Actually, you can choose your own positions to place the adapter. Both Houlsby and Pfeiffer styles can be configured, just set the modified_modules=['attention', 'ff'] or modified_modules=['layer_norm'] (different w.r.t different architectures, please use the visualization module to visualize the architecture). You can even apply adapter drop with modified_modules set to ["6.attention", "7.attention", ...]
